#!/bin/bash

function myprog() {
	# adding comment
	# adding second comment
	cd /home/ubuntu/ip
	curl https://ipinfo.io/ip > ip.txt
	git add -A
	git commit -m "New ip"
	git push origin2 master
}


myprog
