#!/bin/bash

function myprog() {
	cd /home/ubuntu/ip
	curl https://ipinfo.io/ip > ip.txt
	git add -A
	git commit -m "New ip"
	git push origin2 master
	DATE=$(date ) 
	echo -e "$DATE: Successfully pushed I think\n" >> /home/ubuntu/ip/ip.log
}


myprog
